networks:
  laravel:
    name: laravel

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: devops_nginx
    tty: true
    depends_on:
      - php
      - mysql
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devops_php
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  mysql:
    image: mysql:latest
    container_name: devops_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: docker_laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: devops_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    command: ["install", "--ignore-platform-reqs"]
    depends_on:
      - php
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devops_artisan
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "artisan"]
    networks:
      - laravel

  npm:
    image: node:latest
    container_name: devops_npm  
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel

  mailpit:
    image: axllent/mailpit:latest
    container_name: devops_mailpit
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - laravel       
